///////////////////////////////////////////////////////////////////////////////
// tb_top.sv
// ECE 385 Final Project – Real-Time FPGA Video Processing Pipeline
//
// TOP-LEVEL INTEGRATION TESTBENCH
// ─────────────────────────────────────────────────────────────────────────────
// OVERVIEW
// ─────────────────────────────────────────────────────────────────────────────
// This file contains:
//   1. Four behavioural IP STUBS (at the top of this file, before tb_top):
//        clk_wiz_0       – clock generator  (replaces Vivado Clocking Wizard)
//        blk_mem_gen_0   – dual-port BRAM   (replaces Vivado Block Memory Gen)
//        hdmi_tx_0       – HDMI TX          (replaces Real Digital HDMI IP)
//        font_rom        – bitmap font ROM  (replaces AXI lab font_rom.sv)
//
//   2. tb_top – the testbench module itself
//
// WHY STUBS ARE NEEDED
// ─────────────────────────────────────────────────────────────────────────────
// The three Vivado IP blocks (clk_wiz_0, blk_mem_gen_0, hdmi_tx_0) are
// generated by the Vivado IP Catalog and not available as plain .sv files.
// Running them in a standalone behavioural simulation would require either:
//   (a) the full Vivado IP simulation models (.xci + generated RTL), or
//   (b) a behavioural stub that models the observable interface.
//
// The stubs below model only what the testbench needs to verify:
//   clk_wiz_0     : derives exact 25/125/24 MHz clocks from 100 MHz input
//   blk_mem_gen_0 : correct dual-port BRAM read-after-write semantics, 1-cycle
//                   registered read latency on Port B
//   hdmi_tx_0     : accepts colour/sync inputs and drives TMDS pins constant
//   font_rom      : returns 0xFF for non-space glyphs, 0x00 for space
//
// HOW TO USE THESE STUBS IN VIVADO
// ─────────────────────────────────────────────────────────────────────────────
// 1. Add tb_top.sv as a SIMULATION source (not a design source).
// 2. DO NOT add it to synthesis – the real IPs are used for synthesis.
// 3. In Simulation Settings, set the simulation top to `tb_top`.
// 4. Set simulation runtime to "all" (run until $finish).
//
// WHAT THE TESTBENCH VERIFIES
// ─────────────────────────────────────────────────────────────────────────────
//  Test 1 – Reset state
//    Verifies cam_reset_n=1 and cam_pwdn=0 immediately after reset releases.
//    Verifies cam_xclk is toggling (camera gets a clock).
//
//  Test 2 – VGA horizontal timing
//    Runs 4 complete scan lines (4 × 800 pixel_clk cycles).
//    Counts hs pulses, verifies exactly 4 pulses occur.
//    Verifies each hs pulse is 96 cycles wide (pixels 656..751 of each line).
//    Verifies active_nblank is HIGH for pixels 0..639, LOW for 640..799.
//
//  Test 3 – VGA vertical sync present
//    Scans for vs falling edge within 800 × 490 cycles after reset.
//    Verifies vs stays LOW for exactly 2 lines (1600 cycles).
//    (Full frame timing is 800 × 525; this TB verifies the vs pulse shape.)
//
//  Test 4 – VDE (Video Data Enable) active window
//    vde is the output of color_mapper.  Because the filter pipeline has 9
//    stages of latency and text_overlay adds 2, vde is delayed by 11 cycles
//    relative to active_nblank.  The TB accounts for this delay and checks:
//      - vde is HIGH exactly during the active window (after pipeline drain)
//      - vde is LOW during horizontal and vertical blanking
//
//  Test 5 – Test pattern end-to-end (SW[15] = 1)
//    With SW[15]=1 the filter pipeline substitutes a colour-bar test pattern.
//    The TB waits for the VGA scan to reach bar 0 (drawX ∈ [0,127] = white),
//    advances 11 cycles for pipeline latency, and checks that:
//      hdmi_r=4'hF, hdmi_g=4'hF, hdmi_b=4'hF  (white = 4'hF on all channels)
//    Then checks bar 1 (drawX ∈ [128,255]) produces yellow (hdmi_b=0).
//
//  Test 6 – Camera pixel end-to-end
//    Writes a known RGB565 pixel (0xF800 = pure red) at camera position (0,0)
//    via the capture interface.  The pixel travels through:
//      ov7670_capture → blk_mem_gen_0 (write) → blk_mem_gen_0 (read) →
//      filter_pipeline (9 cycles) → text_overlay (2 cycles) → color_mapper
//    With SW=0 (passthrough), expected HDMI output at display position (0,0):
//      R8 = {0b11111, 0b111} = 0xFF → hdmi_r = 4'hF
//      G8 = {0b00000, 0b00} = 0x00  → hdmi_g = 4'h0
//      B8 = {0b00000, 0b000} = 0x00 → hdmi_b = 4'h0
//
//  Test 7 – Grayscale filter (SW[0] = 1)
//    Same pure-red pixel; with grayscale enabled:
//      Y = (77 × 255 + 150 × 0 + 29 × 0) >> 8 = 76
//      hdmi_r = hdmi_g = hdmi_b = 4'h4  (76 >> 4 = 4)
//
//  Test 8 – Reset clears pipeline
//    Assert reset while camera pixels are in flight.
//    After reset releases, verifies outputs go to known state within a few
//    scan lines (no stale data from pre-reset frames).
//
// PIPELINE LATENCY CONSTANT
// ─────────────────────────────────────────────────────────────────────────────
// Total pixel_clk cycles from drawX/drawY to hdmi output:
//   1 (BRAM read address pre-register) +
//   1 (BRAM registered read output)   +
//   9 (filter pipeline)                +
//   2 (text_overlay)                   = 13 cycles
// The TB uses PIPE_LATENCY = 13 when translating scan positions to expected
// output timing.
///////////////////////////////////////////////////////////////////////////////

`timescale 1ns/1ps

// =============================================================================
// STUB 1 – clk_wiz_0
// Behavioural clock generator: derives 25 MHz, 125 MHz, 24 MHz from 100 MHz.
// Port names match top.sv instantiation exactly.
// =============================================================================
module clk_wiz_0 (
    input  logic clk_in1,   // 100 MHz board clock
    input  logic reset,
    output logic clk_out1,  // 25 MHz  – pixel_clk
    output logic clk_out2,  // 125 MHz – tmds_clk
    output logic clk_out3,  // ~24 MHz – cam_clk_int
    output logic locked     // always asserted after short delay
);
    // ── Pixel clock: 100 MHz ÷ 4 = 25 MHz (period 40 ns) ────────────────────
    // Implemented as a counter that divides the input clock by 4.
    logic [1:0] div4_cnt = 0;
    always @(posedge clk_in1 or posedge reset) begin
        if (reset) begin
            div4_cnt <= 0; clk_out1 <= 0;
        end else begin
            div4_cnt <= div4_cnt + 1;
            if (div4_cnt == 2'd1) clk_out1 <= 1;
            if (div4_cnt == 2'd3) clk_out1 <= 0;
        end
    end

    // ── TMDS clock: 125 MHz (period 8 ns) ─────────────────────────────────
    // Not a clean integer divide from 100 MHz, but for simulation purposes
    // we generate it independently at the right frequency.
    initial clk_out2 = 0;
    always #4 clk_out2 = ~clk_out2;   // 8 ns half-period = 125 MHz

    // ── Camera XCLK: 100 MHz ÷ 4 = 25 MHz ────────────────────────────────
    // (Close enough to 24 MHz for simulation; real design uses fractional PLL)
    logic [1:0] div4_cam = 0;
    always @(posedge clk_in1 or posedge reset) begin
        if (reset) begin
            div4_cam <= 0; clk_out3 <= 0;
        end else begin
            div4_cam <= div4_cam + 1;
            if (div4_cam == 2'd1) clk_out3 <= 1;
            if (div4_cam == 2'd3) clk_out3 <= 0;
        end
    end

    // ── Locked: asserted 8 clk_in1 cycles after reset de-asserts ──────────
    logic [2:0] lock_cnt = 0;
    always @(posedge clk_in1 or posedge reset) begin
        if (reset) begin
            locked <= 0; lock_cnt <= 0;
        end else if (!locked) begin
            lock_cnt <= lock_cnt + 1;
            if (lock_cnt == 3'd7) locked <= 1;
        end
    end
endmodule


// =============================================================================
// STUB 2 – blk_mem_gen_0
// Behavioural dual-port BRAM: write port A (cam_pclk), read port B (pixel_clk).
// Port B output is REGISTERED (1-cycle latency), matching the real IP config.
// Depth: 131072 (17-bit address), width: 16 bits.
// =============================================================================
module blk_mem_gen_0 (
    // Port A – Write  (camera clock domain)
    input  logic        clka,
    input  logic        wea,
    input  logic [16:0] addra,
    input  logic [15:0] dina,
    // Port B – Read   (pixel clock domain, registered output)
    input  logic        clkb,
    input  logic [16:0] addrb,
    output logic [15:0] doutb
);
    // ── Memory array ──────────────────────────────────────────────────────────
    // 76800 entries used (320×240); address space is 131072 (17 bits).
    // Initialise to 0x0000 (black in RGB565).
    logic [15:0] mem [0:131071];
    initial begin
        for (int i = 0; i < 131072; i++) mem[i] = 16'h0000;
    end

    // ── Port A: synchronous write ─────────────────────────────────────────────
    always_ff @(posedge clka) begin
        if (wea) mem[addra] <= dina;
    end

    // ── Port B: synchronous registered read (1-cycle output latency) ─────────
    // This matches "Primitives Output Register" checked in the IP wizard.
    always_ff @(posedge clkb) begin
        doutb <= mem[addrb];
    end
endmodule


// =============================================================================
// STUB 3 – hdmi_tx_0
// Behavioural HDMI TX stub.
// Accepts RGB, sync, and VDE inputs.  Drives TMDS pins to 0 (not meaningful
// in simulation; real differential output only has meaning on hardware).
// The TB checks hdmi_r/g/b signals BEFORE they enter this IP.
// =============================================================================
module hdmi_tx_0 (
    input  logic        pix_clk,
    input  logic        pix_clkx5,
    input  logic        pix_clk_locked,
    input  logic        rst,
    input  logic [3:0]  red,
    input  logic [3:0]  green,
    input  logic [3:0]  blue,
    input  logic        hsync,
    input  logic        vsync,
    input  logic        vde,
    input  logic [3:0]  aux0_din,
    input  logic [3:0]  aux1_din,
    input  logic [3:0]  aux2_din,
    input  logic        ade,
    output logic [2:0]  hdmi_tx_p,
    output logic [2:0]  hdmi_tx_n,
    output logic        hdmi_clk_p,
    output logic        hdmi_clk_n
);
    // TMDS outputs are not meaningful in behavioural simulation.
    // Drive to constants so the TB can verify clean logic levels.
    assign hdmi_tx_p  = 3'b111;
    assign hdmi_tx_n  = 3'b000;
    assign hdmi_clk_p = 1'b1;
    assign hdmi_clk_n = 1'b0;
endmodule


// =============================================================================
// STUB 4 – font_rom
// Behavioural font ROM stub (same as in tb_text_overlay.sv).
// 0xFF for any non-space glyph; 0x00 for space (0x20).
// Replace with actual font_rom.sv for hardware-level font testing.
// =============================================================================
module font_rom (
    input  logic        clk,
    input  logic [10:0] addr,
    output logic [7:0]  data
);
    always_ff @(posedge clk)
        data <= (addr[10:4] == 7'h20) ? 8'h00 : 8'hFF;
endmodule


// =============================================================================
// TOP-LEVEL TESTBENCH
// =============================================================================
module tb_top;

    // ── DUT ports ─────────────────────────────────────────────────────────────
    logic        Clk;
    logic        reset_btn;
    logic [15:0] SW;

    logic        cam_pclk;
    logic        cam_xclk;
    wire         cam_siod;      // inout
    logic        cam_sioc;
    logic        cam_vsync;
    logic        cam_href;
    logic [7:0]  cam_data;
    logic        cam_reset_n;
    logic        cam_pwdn;

    logic        hdmi_tmds_clk_n, hdmi_tmds_clk_p;
    logic [2:0]  hdmi_tmds_data_n, hdmi_tmds_data_p;

    // ── Probe wires into DUT internals (hierarchical references) ─────────────
    // These let us observe intermediate signals without ports.
    // Vivado XSim supports hierarchical references in testbenches.
    wire [9:0]  probe_drawX  = dut.drawX;
    wire [9:0]  probe_drawY  = dut.drawY;
    wire        probe_hs     = dut.hs;
    wire        probe_vs     = dut.vs;
    wire        probe_blank  = dut.active_nblank;
    wire [3:0]  probe_hdmi_r = dut.hdmi_r;
    wire [3:0]  probe_hdmi_g = dut.hdmi_g;
    wire [3:0]  probe_hdmi_b = dut.hdmi_b;
    wire        probe_vde    = dut.vde;
    wire        probe_pxclk  = dut.pixel_clk;
    wire        probe_camclk = dut.cam_clk_int;
    wire        probe_config = dut.config_done;

    // BRAM write port (from capture, observable for Test 6)
    wire [16:0] probe_fb_wr_addr = dut.fb_wr_addr;
    wire [15:0] probe_fb_wr_data = dut.fb_wr_data;
    wire        probe_fb_wr_en   = dut.fb_wr_en;

    // ── Error / pass tracking ─────────────────────────────────────────────────
    int total_errors  = 0;
    int test_errors   = 0;

    // ── Timing constants (all in ns; pixel_clk = 40 ns period) ───────────────
    localparam CLK_PERIOD      = 10;   // board clock: 100 MHz
    localparam PIXEL_CLK_NS    = 40;   // pixel_clk:    25 MHz
    localparam PCLK_PERIOD_NS  = 40;   // cam_pclk: use same rate for simplicity

    // VGA parameters (from VGA_controller.sv)
    localparam H_TOTAL         = 800;
    localparam H_ACTIVE        = 640;
    localparam H_SYNC_START    = 656;
    localparam H_SYNC_END      = 752;  // exclusive
    localparam V_TOTAL         = 525;
    localparam V_ACTIVE        = 480;
    localparam V_SYNC_START    = 490;
    localparam V_SYNC_END      = 492;  // exclusive

    // Combined pipeline latency (pixel_clk cycles, drawX/Y → hdmi_r/g/b):
    //   1 (drawX/Y delay reg) + 1 (BRAM out reg) + 9 (filter) + 2 (overlay) = 13
    localparam PIPE_LATENCY = 13;

    // ── DUT ───────────────────────────────────────────────────────────────────
    top dut (
        .Clk             (Clk),
        .reset_btn       (reset_btn),
        .SW              (SW),
        .cam_pclk        (cam_pclk),
        .cam_xclk        (cam_xclk),
        .cam_siod        (cam_siod),
        .cam_sioc        (cam_sioc),
        .cam_vsync       (cam_vsync),
        .cam_href        (cam_href),
        .cam_data        (cam_data),
        .cam_reset_n     (cam_reset_n),
        .cam_pwdn        (cam_pwdn),
        .hdmi_tmds_clk_n (hdmi_tmds_clk_n),
        .hdmi_tmds_clk_p (hdmi_tmds_clk_p),
        .hdmi_tmds_data_n(hdmi_tmds_data_n),
        .hdmi_tmds_data_p(hdmi_tmds_data_p)
    );

    // ── Board clock: 100 MHz ──────────────────────────────────────────────────
    initial Clk = 0;
    always #(CLK_PERIOD/2) Clk = ~Clk;

    // ── Camera PCLK: same rate as pixel_clk for simplicity ───────────────────
    // (Real camera generates its own PCLK from XCLK; in simulation they
    //  are driven independently so we keep them at matching frequencies.)
    initial cam_pclk = 0;
    always #(PCLK_PERIOD_NS/2) cam_pclk = ~cam_pclk;

    // ── SIOD pull-up model ────────────────────────────────────────────────────
    // Open-drain: pull to HIGH when the DUT releases (drives 1'bz).
    logic siod_val;
    assign siod_val = (cam_siod === 1'bz) ? 1'b1 : cam_siod;

    // =========================================================================
    // TASK LIBRARY
    // =========================================================================

    // ── apply_reset: assert reset for N board-clock cycles ───────────────────
    task automatic apply_reset(input int cycles = 8);
        @(negedge Clk); reset_btn = 1;
        repeat(cycles) @(posedge Clk);
        @(negedge Clk); reset_btn = 0;
        // Wait for pixel_clk to stabilise (a few cycles after lock)
        repeat(20) @(posedge probe_pxclk);
    endtask

    // ── wait_pixel_clks: wait N pixel_clk rising edges ────────────────────
    task automatic wait_pixel_clks(input int n);
        repeat(n) @(posedge probe_pxclk);
    endtask

    // ── wait_scan_line: wait for the next drawX == 0 (start of scan line) ──
    task automatic wait_scan_line(input int timeout_lines = 10);
        int cnt = 0;
        @(posedge probe_pxclk);
        while (probe_drawX !== 10'd0 && cnt < timeout_lines * H_TOTAL) begin
            @(posedge probe_pxclk); cnt++;
        end
        if (probe_drawX !== 10'd0) begin
            $error("wait_scan_line: timeout (drawX never reached 0)");
            total_errors++;
        end
    endtask

    // ── wait_for_xy: wait until (drawX, drawY) reaches (tx, ty) ────────────
    // Handles the case where the target position is in the next frame.
    task automatic wait_for_xy(
        input [9:0] tx, ty,
        input int   timeout_frames = 2
    );
        int cnt = 0;
        int max_cycles = timeout_frames * H_TOTAL * V_TOTAL;
        @(posedge probe_pxclk);
        while ((probe_drawX !== tx || probe_drawY !== ty) && cnt < max_cycles) begin
            @(posedge probe_pxclk); cnt++;
        end
        if (probe_drawX !== tx || probe_drawY !== ty) begin
            $error("wait_for_xy: timeout waiting for (%0d,%0d)", tx, ty);
            total_errors++;
        end
    endtask

    // ── check_signal: assert that a signal equals expected value ─────────────
    `define CHECK(expr, msg) \
        if (!(expr)) begin \
            $error("[%0t] FAIL: %s", $time, msg); \
            total_errors++; test_errors++; \
        end else begin \
            $display("[%0t] PASS: %s", $time, msg); \
        end

    // ── count_hs_pulses: count hs falling edges over N scan lines ────────────
    // Returns the count via output argument.
    // Monitors in a fork/join_any pattern with a timeout.
    task automatic count_hs_in_nlines(
        input  int    n_lines,
        output int    pulse_count
    );
        int cyc;
        pulse_count = 0;
        cyc = 0;
        // Run for n_lines worth of pixel_clk cycles
        fork
            begin : counter
                forever begin
                    @(negedge probe_hs);
                    pulse_count++;
                end
            end
            begin : timer
                repeat(n_lines * H_TOTAL + 10) @(posedge probe_pxclk);
                disable counter;
            end
        join
    endtask

    // ── send_camera_pixel: inject one RGB565 pixel into the capture module ──
    // Drives cam_vsync, cam_href, cam_data, cam_pclk for two bytes.
    task automatic send_camera_pixel(input [15:0] pixel_rgb565);
        // High byte
        @(negedge cam_pclk);
        cam_href = 1;
        cam_data = pixel_rgb565[15:8];
        @(posedge cam_pclk);
        // Low byte
        @(negedge cam_pclk);
        cam_data = pixel_rgb565[7:0];
        @(posedge cam_pclk);
        @(negedge cam_pclk);
        cam_href = 0;
    endtask

    // ── send_camera_frame_start: pulse VSYNC to reset frame counters ──────────
    task automatic send_camera_frame_start();
        @(negedge cam_pclk);
        cam_vsync = 1;
        cam_href  = 0;
        repeat(4) @(posedge cam_pclk);
        @(negedge cam_pclk);
        cam_vsync = 0;
        repeat(2) @(posedge cam_pclk);
    endtask

    // ── send_camera_row: stream one full QVGA row (320 pixels) ────────────────
    // All pixels set to the same value for simplicity.
    task automatic send_camera_row(input [15:0] pixel_val);
        for (int c = 0; c < 320; c++) begin
            // High byte
            @(negedge cam_pclk); cam_href = 1; cam_data = pixel_val[15:8];
            @(posedge cam_pclk);
            // Low byte
            @(negedge cam_pclk); cam_data = pixel_val[7:0];
            @(posedge cam_pclk);
        end
        // Horizontal blanking gap
        @(negedge cam_pclk); cam_href = 0;
        repeat(4) @(posedge cam_pclk);
    endtask

    // ── measure_pulse_width: count cycles a signal is LOW ─────────────────────
    task automatic measure_low_pulse(
        input  logic sig,
        output int   width_cycles,
        input  int   max_wait = 1000
    );
        int cnt = 0;
        // Wait for signal to go low
        while (sig !== 1'b0 && cnt < max_wait) begin @(posedge probe_pxclk); cnt++; end
        if (sig !== 1'b0) begin
            $error("measure_low_pulse: signal never went low");
            total_errors++; width_cycles = -1; return;
        end
        // Count how long it stays low
        width_cycles = 0;
        while (sig === 1'b0) begin @(posedge probe_pxclk); width_cycles++; end
    endtask

    // =========================================================================
    // MAIN TEST SEQUENCE
    // =========================================================================
    initial begin
        $dumpfile("tb_top.vcd");
        $dumpvars(0, tb_top);

        // ── Initialise all inputs ─────────────────────────────────────────────
        reset_btn = 0;
        SW        = 16'h0000;
        cam_vsync = 1;    // VSYNC HIGH = blanking (camera not outputting)
        cam_href  = 0;
        cam_data  = 8'h00;

        $display("\n╔══════════════════════════════════════════════════════╗");
        $display("║  ECE 385 Video Pipeline – Top-Level Testbench        ║");
        $display("╚══════════════════════════════════════════════════════╝\n");

        // ─────────────────────────────────────────────────────────────────────
        // TEST 1 – RESET STATE
        // Verifies camera control pins are correct after reset.
        // cam_reset_n must be HIGH (camera active).
        // cam_pwdn   must be LOW  (camera powered).
        // cam_xclk   must be toggling (clock reaches camera).
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 1: Reset State ═══");
        test_errors = 0;

        apply_reset(10);

        // Sample after a few pixel_clk cycles
        wait_pixel_clks(5);

        `CHECK(cam_reset_n === 1'b1,
               "cam_reset_n is HIGH (camera not in hardware reset)")
        `CHECK(cam_pwdn === 1'b0,
               "cam_pwdn is LOW (camera powered on)")

        // Verify cam_xclk is toggling: measure one half-period
        begin
            logic prev_xclk;
            int   toggle_cnt;
            prev_xclk  = probe_camclk;
            toggle_cnt = 0;
            repeat(20) begin
                @(posedge Clk);
                if (probe_camclk !== prev_xclk) toggle_cnt++;
                prev_xclk = probe_camclk;
            end
            `CHECK(toggle_cnt >= 2,
                   "cam_xclk is toggling (camera receives master clock)")
        end

        $display("Test 1: %0d error(s)\n", test_errors);
        total_errors += test_errors;

        // ─────────────────────────────────────────────────────────────────────
        // TEST 2 – VGA HORIZONTAL TIMING
        // Counts hs pulses across 4 scan lines.
        // Checks hs pulse width = 96 pixel_clk cycles (H_SYNC_END - H_SYNC_START).
        // Checks active_nblank is HIGH for pixels 0..639, LOW for 640..799.
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 2: VGA Horizontal Timing ═══");
        test_errors = 0;

        // Wait for start of a fresh scan line
        wait_scan_line(5);
        wait_pixel_clks(2);   // settle

        // Count hs pulses over 4 lines
        begin
            int pulse_cnt;
            count_hs_in_nlines(4, pulse_cnt);
            `CHECK(pulse_cnt == 4,
                   $sformatf("hs pulse count over 4 lines = %0d (expected 4)", pulse_cnt))
        end

        // Measure hs pulse width (should be 96 pixel_clk cycles)
        begin
            int pw;
            measure_low_pulse(probe_hs, pw, 1000);
            `CHECK(pw == 96,
                   $sformatf("hs pulse width = %0d cycles (expected 96)", pw))
        end

        // Check active_nblank at a known position
        // Wait until drawX = 300 on any line and check it is HIGH
        wait_for_xy(10'd300, probe_drawY, 2);
        `CHECK(probe_blank === 1'b1,
               "active_nblank HIGH at drawX=300 (inside active region)")

        // Wait until drawX = 660 and check it is LOW
        wait_for_xy(10'd660, probe_drawY, 2);
        `CHECK(probe_blank === 1'b0,
               "active_nblank LOW at drawX=660 (inside blanking)")

        $display("Test 2: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // TEST 3 – VGA VERTICAL SYNC SHAPE
        // Finds the vs falling edge (start of vs pulse) and measures its width.
        // vs is active-low; pulse lasts 2 scan lines = 1600 pixel_clk cycles.
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 3: VGA Vertical Sync ═══");
        test_errors = 0;

        begin
            int vs_width;
            int wait_cnt = 0;
            // Scan forward until vs goes low; timeout after 500 lines
            while (probe_vs !== 1'b0 && wait_cnt < V_TOTAL * H_TOTAL) begin
                @(posedge probe_pxclk); wait_cnt++;
            end
            if (probe_vs !== 1'b0) begin
                $error("vs never went LOW (vs pulse not found)");
                total_errors++; test_errors++;
            end else begin
                $display("[%0t] vs pulse detected, measuring width...", $time);
                vs_width = 0;
                while (probe_vs === 1'b0) begin
                    @(posedge probe_pxclk); vs_width++;
                end
                // Expected: 2 lines × 800 cycles = 1600 cycles
                `CHECK(vs_width >= 1595 && vs_width <= 1605,
                       $sformatf("vs pulse width = %0d cycles (expected ~1600)", vs_width))
            end
        end

        $display("Test 3: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // TEST 4 – VDE (VIDEO DATA ENABLE) ACTIVE WINDOW
        // vde is produced by color_mapper and is delayed PIPE_LATENCY cycles
        // behind the VGA scan position.
        // Checks:
        //   - vde goes HIGH exactly PIPE_LATENCY cycles after drawX enters
        //     the active region (drawX=0 with drawY in active range)
        //   - vde goes LOW exactly PIPE_LATENCY cycles after drawX exits
        //     the active region (drawX=640)
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 4: VDE Active Window Timing ═══");
        test_errors = 0;

        // Wait for start of an active scan line (drawY in active range)
        begin
            int cnt = 0;
            while ((probe_drawX !== 10'd0 || probe_drawY >= 10'd480)
                   && cnt < H_TOTAL * V_TOTAL) begin
                @(posedge probe_pxclk); cnt++;
            end

            // At drawX=0, drawY < 480: advance PIPE_LATENCY cycles
            // and check vde has gone HIGH
            wait_pixel_clks(PIPE_LATENCY + 1);
            `CHECK(probe_vde === 1'b1,
                   $sformatf("vde HIGH %0d cycles after active-region start", PIPE_LATENCY))
        end

        // Find drawX=640 (end of active) and check vde goes LOW after pipeline
        begin
            wait_for_xy(10'd640, probe_drawY, 2);
            wait_pixel_clks(PIPE_LATENCY + 1);
            `CHECK(probe_vde === 1'b0,
                   "vde LOW after PIPE_LATENCY cycles past active region end")
        end

        $display("Test 4: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // TEST 5 – TEST PATTERN END-TO-END (SW[15] = 1)
        // The filter_pipeline substitutes a colour-bar pattern.
        // Bar 0 (drawX in 0..127)   → WHITE  = 0xFFFFFF → hdmi_r/g/b = 4'hF
        // Bar 1 (drawX in 128..255) → YELLOW = 0xFFFF00 → hdmi_b = 4'h0
        // After PIPE_LATENCY cycles the HDMI channels should reflect these.
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 5: Colour-Bar Test Pattern ═══");
        test_errors = 0;

        SW = 16'h8000;   // SW[15] = test pattern
        wait_pixel_clks(5);  // let sync flops settle

        // Position to start of row, then advance to where bar 0 output exits pipeline
        begin
            wait_for_xy(10'd0, 10'd50, 2);  // row 50 (well inside active area)
            // Advance to where drawX = bar0_centre = 64; then add PIPE_LATENCY
            // Bar 0 is drawX 0..127; we wait to drawX=64 and then PIPE_LATENCY more
            wait_for_xy(10'd64, 10'd50, 2);
            wait_pixel_clks(PIPE_LATENCY);

            // Now output should correspond to bar 0 = WHITE
            `CHECK(probe_hdmi_r === 4'hF, "T5 bar0: hdmi_r=0xF (white)")
            `CHECK(probe_hdmi_g === 4'hF, "T5 bar0: hdmi_g=0xF (white)")
            `CHECK(probe_hdmi_b === 4'hF, "T5 bar0: hdmi_b=0xF (white)")
            `CHECK(probe_vde === 1'b1,    "T5: vde HIGH during active video")
        end

        // Check bar 1 = YELLOW (hdmi_b = 0)
        begin
            wait_for_xy(10'd192, 10'd50, 2);  // centre of bar 1 (128..255)
            wait_pixel_clks(PIPE_LATENCY);
            `CHECK(probe_hdmi_r === 4'hF, "T5 bar1: hdmi_r=0xF (yellow)")
            `CHECK(probe_hdmi_g === 4'hF, "T5 bar1: hdmi_g=0xF (yellow)")
            `CHECK(probe_hdmi_b === 4'h0, "T5 bar1: hdmi_b=0x0 (yellow = no blue)")
        end

        // Check bar 7 = BLACK (drawX 448..511 → centre 480)
        begin
            wait_for_xy(10'd480, 10'd50, 2);
            wait_pixel_clks(PIPE_LATENCY);
            `CHECK(probe_hdmi_r === 4'h0, "T5 bar7: hdmi_r=0 (black)")
            `CHECK(probe_hdmi_g === 4'h0, "T5 bar7: hdmi_g=0 (black)")
            `CHECK(probe_hdmi_b === 4'h0, "T5 bar7: hdmi_b=0 (black)")
        end

        SW = 16'h0000;   // back to camera mode
        $display("Test 5: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // TEST 6 – CAMERA PIXEL END-TO-END
        // Writes a pure-red pixel (0xF800) at camera position (row=0, col=0).
        // With SW=0 the pipeline is a passthrough.
        // Expected at display (0,0) after PIPE_LATENCY cycles:
        //   R8 = 0xFF → hdmi_r = 4'hF
        //   G8 = 0x00 → hdmi_g = 4'h0
        //   B8 = 0x00 → hdmi_b = 4'h0
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 6: Camera Pixel End-to-End ═══");
        test_errors = 0;

        SW = 16'h0000;

        // Step A: Write red pixel to BRAM via camera capture
        send_camera_frame_start();       // VSYNC → resets row/col counters
        // Send rows 0 padding (just the first pixel matters)
        @(negedge cam_pclk); cam_href = 1;
        // Send pixel (0,0) = 0xF800 (pure red)
        cam_data = 8'hF8;  // high byte: R=11111, G[5:3]=000
        @(posedge cam_pclk);
        @(negedge cam_pclk);
        cam_data = 8'h00;  // low byte:  G[2:0]=000, B=00000
        @(posedge cam_pclk);
        @(negedge cam_pclk); cam_href = 0;

        // Verify the BRAM write happened
        wait_pixel_clks(5);
        `CHECK(probe_fb_wr_en === 1'b0,
               "T6: wr_en deasserted after pixel write completes")

        // Step B: Scan to display position (0,0) and check output
        wait_for_xy(10'd0, 10'd0, 3);    // wait for frame start
        wait_pixel_clks(PIPE_LATENCY + 2);

        `CHECK(probe_hdmi_r === 4'hF, "T6: hdmi_r=0xF (red pixel R channel)")
        `CHECK(probe_hdmi_g === 4'h0, "T6: hdmi_g=0x0 (red pixel G channel)")
        `CHECK(probe_hdmi_b === 4'h0, "T6: hdmi_b=0x0 (red pixel B channel)")
        `CHECK(probe_vde === 1'b1,    "T6: vde HIGH at active pixel")

        $display("Test 6: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // TEST 7 – GRAYSCALE FILTER (SW[0] = 1)
        // Same pure-red pixel as Test 6.
        // Grayscale: Y = (77*255 + 0 + 0) >> 8 = 76 = 0x4C
        // hdmi_r = hdmi_g = hdmi_b = 0x4C >> 4 = 4'h4
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 7: Grayscale Filter SW[0]=1 ═══");
        test_errors = 0;

        SW = 16'h0001;   // enable grayscale
        wait_pixel_clks(5);   // let sync flops settle (2 cycles needed)

        // The BRAM still contains the red pixel from Test 6.
        // Scan to display (0,0) on the next frame.
        wait_for_xy(10'd0, 10'd0, 3);
        wait_pixel_clks(PIPE_LATENCY + 2);

        // Y = (77 * 255) >> 8 = 76 = 0x4C; upper nibble = 4
        `CHECK(probe_hdmi_r === 4'h4,
               $sformatf("T7: hdmi_r=%0h expected 4 (gray of red)", probe_hdmi_r))
        `CHECK(probe_hdmi_g === 4'h4,
               $sformatf("T7: hdmi_g=%0h expected 4 (gray = R)", probe_hdmi_g))
        `CHECK(probe_hdmi_b === 4'h4,
               $sformatf("T7: hdmi_b=%0h expected 4 (gray = R)", probe_hdmi_b))

        SW = 16'h0000;
        $display("Test 7: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // TEST 8 – FULL ROW PIXEL UNIFORMITY
        // Writes an entire row of pure-green pixels (0x07E0).
        // Scans across that row in the display and verifies every pixel in the
        // active region produces the same HDMI output.
        // Checks PIPE_LATENCY alignment is consistent across the full row.
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 8: Full Row Uniformity ═══");
        test_errors = 0;

        SW = 16'h0000;

        // Write a full row of green at camera row 10
        send_camera_frame_start();
        // Skip rows 0..9 (send them as black so row 10 stands out)
        for (int r = 0; r < 10; r++) send_camera_row(16'h0000);
        send_camera_row(16'h07E0);   // row 10 = pure green

        // Wait until VGA reaches display row 20 (= camera row 10 × 2)
        wait_for_xy(10'd0, 10'd20, 3);
        // Scan PIPE_LATENCY cycles ahead
        wait_pixel_clks(PIPE_LATENCY + 1);

        // G8 = {G6=111111, G6[5:4]=11} = 0xFF; hdmi_g = 4'hF
        // R8 = 0, B8 = 0 → hdmi_r = hdmi_b = 0
        // Check 20 consecutive pixels in the row
        begin
            int mismatches = 0;
            for (int px = 0; px < 20; px++) begin
                if (probe_hdmi_r !== 4'h0 || probe_hdmi_g !== 4'hF || probe_hdmi_b !== 4'h0)
                    mismatches++;
                @(posedge probe_pxclk);
            end
            `CHECK(mismatches == 0,
                   $sformatf("T8: all 20 green pixels correct (mismatches=%0d)", mismatches))
        end

        $display("Test 8: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // TEST 9 – RESET CLEARS PIPELINE
        // Assert reset while valid pixels are in the pipeline.
        // After reset releases and pipeline drains, the output should go to
        // black (BRAM is zeroed, pipeline flushed to 0).
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 9: Reset Clears Pipeline ═══");
        test_errors = 0;

        SW = 16'h0000;

        // Apply reset mid-frame
        apply_reset(8);

        // Run 2 full scan lines to let pipeline drain
        wait_pixel_clks(2 * H_TOTAL + PIPE_LATENCY + 10);

        // During active video, BRAM was zeroed at init; output should be black
        wait_for_xy(10'd300, 10'd100, 3);
        wait_pixel_clks(PIPE_LATENCY + 1);

        `CHECK(probe_vde === 1'b1, "T9: vde HIGH during active region post-reset")
        `CHECK(probe_hdmi_r === 4'h0, "T9: hdmi_r=0 (black) post-reset")
        `CHECK(probe_hdmi_g === 4'h0, "T9: hdmi_g=0 (black) post-reset")
        `CHECK(probe_hdmi_b === 4'h0, "T9: hdmi_b=0 (black) post-reset")

        $display("Test 9: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // TEST 10 – SCCB ACTIVITY AFTER RESET
        // After reset releases, the ov7670_init module should begin sending
        // SCCB transactions.  We verify that cam_sioc starts toggling within
        // a reasonable number of cam_clk cycles (after the power-up delay).
        // We do NOT verify the exact bit pattern here (that is tb_ov7670_sccb).
        // Just check that the SCCB bus becomes active.
        // ─────────────────────────────────────────────────────────────────────
        $display("═══ Test 10: SCCB Activity After Reset ═══");
        test_errors = 0;

        apply_reset(8);

        begin
            int sioc_toggle = 0;
            logic prev_sioc;
            int   cnt = 0;
            prev_sioc = cam_sioc;

            // Wait up to 2,000,000 cam_clk cycles (covers PWRUP_DELAY=1.2M + margin)
            // We check every 100 cycles to avoid extreme event overhead
            while (sioc_toggle < 10 && cnt < 2_000_000) begin
                @(posedge probe_camclk); cnt++;
                if (cam_sioc !== prev_sioc) sioc_toggle++;
                prev_sioc = cam_sioc;
            end

            `CHECK(sioc_toggle >= 10,
                   $sformatf("T10: SIOC toggled %0d times (SCCB init active)", sioc_toggle))
        end

        $display("Test 10: %0d error(s)\n", test_errors);

        // ─────────────────────────────────────────────────────────────────────
        // FINAL REPORT
        // ─────────────────────────────────────────────────────────────────────
        $display("\n╔══════════════════════════════════════════════════════╗");
        $display("║               SIMULATION COMPLETE                    ║");
        $display("╠══════════════════════════════════════════════════════╣");
        if (total_errors == 0)
            $display("║  ALL TESTS PASSED  (0 errors)                        ║");
        else
            $display("║  FAILED – %0d total error(s) detected                  ║",
                     total_errors);
        $display("╚══════════════════════════════════════════════════════╝\n");

        $finish;
    end

    // =========================================================================
    // WAVEFORM ANNOTATION
    // These $monitor statements print key state changes to the TCL console.
    // Disable them with // if the console becomes too verbose.
    // =========================================================================
    //
    // Print every time vde changes (marks active/blanking transitions):
    // initial $monitor("[%0t] vde=%0b hs=%0b vs=%0b drawX=%0d drawY=%0d r=%0h g=%0h b=%0h",
    //                  $time, probe_vde, probe_hs, probe_vs,
    //                  probe_drawX, probe_drawY,
    //                  probe_hdmi_r, probe_hdmi_g, probe_hdmi_b);

endmodule
